FROM node:20-alpine

WORKDIR /app

# Set build-time variables (ARG) and runtime environment variables (ENV)
ARG HYGRAPH_URL
ARG VITE_HYGRAPH_KEY
ARG TOOLGANKELIJK_AUDIT_URL
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_USER
ARG SMTP_PASS

ENV HYGRAPH_URL=$HYGRAPH_URL
ENV VITE_HYGRAPH_KEY=$VITE_HYGRAPH_KEY
ENV TOOLGANKELIJK_AUDIT_URL=$TOOLGANKELIJK_AUDIT_URL
ENV SMTP_HOST=$SMTP_HOST
ENV SMTP_PORT=$SMTP_PORT
ENV SMTP_USER=$SMTP_USER
ENV SMTP_PASS=$SMTP_PASS

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

RUN npm run build

CMD ["npm", "run", "start"]